### ISSUE TITLE
No module named 'billy_metadata' while running convert_metadata.py

### ISSUE THREAD

**Issue by pmathur5k10** [openstates/openstates#1477]
Trying to convert billy to pupa for state ma (massachusetts)

```
puneet@puneet_work MINGW64 ~/openstates (master)
$ ./scripts/convert_metadata.py ma> openstates/ma/__init__.py
Traceback (most recent call last):
  File "./scripts/convert_metadata.py", line 142, in <module>
    convert(sys.argv[1])
  File "./scripts/convert_metadata.py", line 44, in convert
    metadata = importlib.import_module('billy_metadata.' + state).metadata
  File "C:\Python34\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'billy_metadata'
```

**Comment by jamesturk** [comment]
can you show the result of

import sys;  print(sys.path)

from that virtualenv?
