### ISSUE TITLE
DE: Committee scraper is not working

### ISSUE THREAD

**Issue by hiteshgarg14** [openstates/openstates#1497]
I found that it is scrapping URL without JavaScript loaded data.
That's why there are no 'tr' and 'td' tags in scrapped HTML code resulting in the error:-
```
Traceback (most recent call last):
  File "/usr/local/bin/billy-update", line 9, in <module>
    load_entry_point('billy==1.9.0', 'console_scripts', 'billy-update')()
  File "/opt/openstates/billy/billy/bin/update.py", line 368, in main
    run_record += _run_scraper(stype, args, metadata)
  File "/opt/openstates/billy/billy/bin/update.py", line 102, in _run_scraper
    scraper.scrape(chamber, time)
  File "/srv/openstates-web/openstates/de/committees.py", line 41, in scrape
    comm = row.xpath('.//a')[1]
IndexError: list index out of range
```
this is happening for all terms.

**Comment by jamesturk** [comment]
see #1445
