### ISSUE TITLE
AZ: Events scraper is failing and needs update for 2017

### ISSUE THREAD

**Issue by hiteshgarg14** [openstates/openstates#1571]
State: AZ

[URL](http://www.azleg.gov/CommitteeAgendas.asp?Body=S) that is being used to scrap the events is giving HTTPError: 500 (Internal Server Error)

```
Traceback (most recent call last):
  File "/opt/openstates/venv-pupa//bin/pupa", line 11, in <module>
    load_entry_point('pupa', 'console_scripts', 'pupa')()
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/__main__.py", line 67, in main
    subcommands[args.subcommand].handle(args, other)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 288, in handle
    report['scrape'] = self.do_scrape(juris, args, scrapers)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 166, in do_scrape
    report[scraper_name] = scraper.do_scrape(**scrape_args)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/scrape/base.py", line 101, in do_scrape
    for obj in self.scrape(**kwargs) or []:
  File "/opt/openstates/openstates/openstates/az/events.py", line 31, in scrape
    yield from self.scrape_chamber(chamber)
  File "/opt/openstates/openstates/openstates/az/events.py", line 44, in scrape_chamber
    html_ = self.get(url).text
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/scrapelib/__init__.py", line 272, in request
    raise HTTPError(resp)
scrapelib.HTTPError: 500 while retrieving http://www.azleg.gov/CommitteeAgendas.asp?Body=S
```

**Comment by hiteshgarg14** [comment]
@jamesturk @mileswwatkins It seems like on [openstates](https://openstates.org/az/events/?month=5&year=2016) same event is listed many times, for example, look for an event on 3 may 2016 and I didn't find that committee meeting on the official [page](http://www.azleg.gov/archivedmeetings/?Year=2016).
I am not sure about the [URL](http://www.azleg.gov/archivedmeetings/), I am considering to scrap events. If I am right then, I would like to write a new scraper for this one. otherwise please let me know about correct URL to consider for scraping.

**Comment by hiteshgarg14** [comment]
Events Scraper is still not working. As the  [URL](http://www.azleg.gov/CommitteeAgendas.asp?Body=S) that is being used to scrap the events is giving HTTPError: 500 (Internal Server Error)

**Comment by jamesturk** [comment]
closing all event scraper issues
