### ISSUE TITLE
IL: committees scraper is broken

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#1833]
State: IL

```
  people: {}
Traceback (most recent call last):
  File "/opt/openstates/venv-pupa//bin/pupa", line 11, in 
no pupa_settings on path, using defaults
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/__main__.py", line 67, in main
    subcommands[args.subcommand].handle(args, other)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 260, in handle
    return self.do_handle(args, other, juris)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 305, in do_handle
    report['scrape'] = self.do_scrape(juris, args, scrapers)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 173, in do_scrape
    report[scraper_name] = scraper.do_scrape(**scrape_args)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/scrape/base.py", line 99, in do_scrape
    for obj in self.scrape(**kwargs) or []:
  File "/opt/openstates/openstates/openstates/il/committees.py", line 60, in scrape
    o_id = COMMITTEES[(name, code)]

KeyError: ('Comm. On State & Pension Fund Inves', 'SSPF')
```

@fgregg can you document how to update the _committees file?

**Comment by jamesturk** [comment]
oops, duplicates #1826
