### ISSUE TITLE
Add Pupa database as a Docker Compose service

### ISSUE THREAD

**Issue by pqnelson** [openstates/openstates#1851]
State: N/A (or all of them)

A recent commit [to import all states](https://github.com/openstates/openstates/commit/201cae14a2df97daca9cd50eb6e322cdbce9c856) changes the parameters for Pupa update to also import the scrapped data into a PostgreSQL db. (Or, at least, this is what I can surmise `pupa update --import ...` does, and the [Pupa's `travis.yaml`](https://github.com/opencivicdata/pupa/blob/master/.travis.yml) seems to support this conjecture.)

I noticed this after pulling down the latest changes this morning, then trying to scrape & import CA bills.

There is an exception thrown, and here's the stacktrace in all its glory:

```
$ docker-compose run --rm scrape ca
...
12:16:30 INFO pupa: save bill ACA8 in 20172018 as bill_acf6363c-6b13-11e7-b501-0242ac120005.json
12:16:30 INFO pupa: save bill ACA9 in 20172018 as bill_acfd0034-6b13-11e7-b501-0242ac120005.json
Traceback (most recent call last):
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 307, in do_handle
    report['import'] = self.do_import(juris, args)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 201, in do_import
    with transaction.atomic():
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/transaction.py", line 158, in __enter__
    if not connection.get_autocommit():
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/backends/base/base.py", line 385, in get_autocommit
    self.ensure_connection()
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/openstates/venv-pupa//bin/pupa", line 11, in <module>
    load_entry_point('pupa', 'console_scripts', 'pupa')()
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/__main__.py", line 67, in main
    subcommands[args.subcommand].handle(args, other)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 260, in handle
    return self.do_handle(args, other, juris)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 314, in do_handle
    save_report(report, juris.jurisdiction_id)
  File "/usr/lib/python3.5/contextlib.py", line 29, in inner
    with self._recreate_cm():
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/transaction.py", line 158, in __enter__
    if not connection.get_autocommit():
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/backends/base/base.py", line 385, in get_autocommit
    self.ensure_connection()
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
```

**Comment by jamesturk** [comment]
ah sorry about that- for now you can run w/ --scrape and it'll skip the import

running the scrape into a DB is a bit more complex so we'll likely need to update the directions/docker file for that

**Comment by estaub** [comment]
@showerst If you've cycles, this is another area where getting-started doc would enable folks trying to  fix import-phase bugs, e.g. #1965 .

**Comment by yogiii363** [comment]
I am currently having this issue for all states. Can someone help me with it.

**Comment by jmcarp** [comment]
Done in #2354.
