### ISSUE TITLE
MO :  Committee scraper failing

### ISSUE THREAD

**Issue by yogiii363** [openstates/openstates#2365]
State:

 MO (possibly all)

I am having issue similar to that of #1851 .  For every scrape I am having an exception. Just started yesterday I followed all steps but having this issue for every state.

The exception thrown is : 

>  22:55:13 WARNING scrapelib: got HTTPConnectionPool(host='www.house.mo.gov', port=80): Max retries exceeded with url: /CommitteeHierarchy.aspx (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f408f9f5160>, 'Connection to www.house.mo.gov timed out. (connect timeout=60)')) sleeping for 40 seconds before retry
Traceback (most recent call last):
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/urllib3/connection.py", line 146, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f4076045668>, 'Connection to www.house.mo.gov timed out. (connect timeout=60)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 168, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/openstates/venv-pupa//bin/pupa", line 11, in <module>
    load_entry_point('pupa', 'console_scripts', 'pupa')()
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/__main__.py", line 68, in main
    subcommands[args.subcommand].handle(args, other)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 260, in handle
    return self.do_handle(args, other, juris)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 314, in do_handle
    save_report(report, juris.jurisdiction_id)
  File "/usr/lib/python3.6/contextlib.py", line 51, in inner
    with self._recreate_cm():
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/transaction.py", line 147, in __enter__
    if not connection.get_autocommit():
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/backends/base/base.py", line 378, in get_autocommit
    self.ensure_connection()
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 168, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?

**Comment by jamesturk** [comment]
this issue is related to not having a local postgres running, if you pass --scrape the scrape will succeed or you can get PG running and this will work (or give the correct error at least)
