### ISSUE TITLE
TX: Avoid IP address filtering/rate-limiting

### ISSUE THREAD

**Issue by jmillxyz** [openstates/openstates#2499]
State: TX

Running the scrape for all TX data will result in getting your IP address banned/filtered (though this could also be due to me running multiple scrapes as I understand more of the project).

```
curl ftp://ftp.legis.state.tx.us/bills/851/billtext/html/house_bills/HB00001_HB00099/HB00001E.htm -vvv
*   Trying 204.65.69.25...
* TCP_NODELAY set
* Connection failed
* connect to 204.65.69.25 port 21 failed: Connection refused
* Failed to connect to ftp.legis.state.tx.us port 21: Connection refused
* Closing connection 0
curl: (7) Failed to connect to ftp.legis.state.tx.us port 21: Connection refused
```

Here's the stacktrace from pupa:

```
$  docker-compose up -d postgres && docker-compose run --rm scrape tx
 -- snip --
16:10:59 INFO pupa: Searching an FTP folder for files (bills/851/analysis/html/senate_bills/SB00001_SB00099)
16:11:00 WARNING pupa: could not save RunPlan, no successful runs of ocd-jurisdiction/country:us/state:tx/government yet
Traceback (most recent call last):
  File "/opt/openstates/venv-pupa//bin/pupa", line 11, in <module>
    load_entry_point('pupa', 'console_scripts', 'pupa')()
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/__main__.py", line 68, in main
    subcommands[args.subcommand].handle(args, other)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 260, in handle
    return self.do_handle(args, other, juris)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 305, in do_handle
    report['scrape'] = self.do_scrape(juris, args, scrapers)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 173, in do_scrape
    report[scraper_name] = scraper.do_scrape(**scrape_args)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/scrape/base.py", line 111, in do_scrape
    for obj in self.scrape(**kwargs) or []:
  File "/opt/openstates/openstates/openstates/tx/bills.py", line 82, in scrape
    for item in analysis_files:
  File "/opt/openstates/openstates/openstates/tx/bills.py", line 54, in _get_ftp_files
    for item in self._get_ftp_files(root, '/'.join([dir_, name])):
  File "/opt/openstates/openstates/openstates/tx/bills.py", line 54, in _get_ftp_files
    for item in self._get_ftp_files(root, '/'.join([dir_, name])):
  File "/opt/openstates/openstates/openstates/tx/bills.py", line 33, in _get_ftp_files
    ftp = ftplib.FTP(root)
  File "/usr/lib/python3.6/ftplib.py", line 117, in __init__
    self.connect(host)
  File "/usr/lib/python3.6/ftplib.py", line 152, in connect
    source_address=self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

As a workaround, I used a VPN. So that my VPN server also didn't get rate-limited, I specified `bills`, since that's all I'm missing:
```
$ docker-compose run scrape tx bills
```

Is there a more robust method other states have used? Does anyone know how long the rate-limited period lasts?

**Comment by showerst** [comment]
I just ran a scrape for bills and didn't get banned, i wonder if one of the other scrapers needs a delay in between some of its faster fetches.

There's also an argument to limit the rate we fetch at, out of curiosity, try it with:
```
docker-compose run scrape tx bills --rpm=30
```
(might not need the -- in front of rpm there, not 100% sure when using docker)

**Comment by jmillxyz** [comment]
I'll try that, thanks @showerst!

**Comment by showerst** [comment]
No problem. If it doesn't work, let us know and we can look into a code change. I believe we can set a suggestion per state with something like self.RPM in the code.

**Comment by jamesturk** [comment]
going to close this out for now 👍
