### ISSUE TITLE
FL: Error with party affiliations

### ISSUE THREAD

**Issue by Zirvent** [openstates/openstates#2701]
Hi!
I’ve tried to set up scraper instance and I’ve got an error while parsing people (example for Florida, but error was at other states too). It looks like:

> pupa.exceptions.UnresolvedIdError: cannot resolve pseudo id to Organization: ~{“classification”: “party”, “name”: “Democratic”}

Do you have any suggestions how to manage this situation with parties? I didn’t find a way how to add them to my DB or smth.
Thank you in advance!

full traceback:

Traceback (most recent call last):
File "/opt/openstates/venv-pupa//bin/pupa", line 11, in <module>
  load_entry_point('pupa', 'console_scripts', 'pupa')()
File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/__main__.py", line 68, in main
  subcommands[args.subcommand].handle(args, other)
File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 262, in handle
  return self.do_handle(args, other, juris)
File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 310, in do_handle
  report['import'] = self.do_import(juris, args)
File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 213, in do_import
  report.update(membership_importer.import_directory(datadir))
File "/opt/openstates/venv-pupa/src/pupa/pupa/importers/base.py", line 196, in import_directory
  return self.import_data(json_stream())
File "/opt/openstates/venv-pupa/src/pupa/pupa/importers/base.py", line 233, in import_data
  obj_id, what = self.import_item(data)
File "/opt/openstates/venv-pupa/src/pupa/pupa/importers/base.py", line 254, in import_item
  data = self.prepare_for_db(data)
File "/opt/openstates/venv-pupa/src/pupa/pupa/importers/memberships.py", line 47, in prepare_for_db
  data['organization_id'] = self.org_importer.resolve_json_id(data['organization_id'])
File "/opt/openstates/venv-pupa/src/pupa/pupa/importers/base.py", line 171, in resolve_json_id
  raise UnresolvedIdError(errmsg)
pupa.exceptions.UnresolvedIdError: cannot resolve pseudo id to Organization: ~{"classification": "party", "name": "Democratic"}

**Comment by jamesturk** [comment]
Hi, we don't provide support for running the legislator scrapers locally- I'd recommend you use the API or use the https://github.com/openstates/people repo
