### ISSUE TITLE
MI: Missing bills in 2019-2020

### ISSUE THREAD

**Issue by jessemortenson** [openstates/openstates#3029]
State: MI - Michigan

We found a bunch of bills missing from OpenStates for this jurisdiction and session, including:

[HB 4852](https://www.legislature.mi.gov/(S(4cewuxqvris3xuspgngsdh5t))/mileg.aspx?page=getObject&objectName=2019-HB-4852)
HB 4868
HB 4869
HB 4870
[SB 452](https://www.legislature.mi.gov/(S(qfybxzgtuheeke4q2byj2hkx))/mileg.aspx?page=getObject&objectName=2019-SB-0452)

Investigated by attempting to run the bill scrape locally:

```
jesse@greenbookx:~/repo/civiceagle/openstates$ docker-compose -f hybrid-compose.yml run --rm scrape mi bills --scrape
loaded Open States pupa settings...
mi (scrape)
  bills: {}
20:06:49 INFO pupa: save jurisdiction Michigan as jurisdiction_ocd-jurisdiction-country:us-state:mi-government.json
20:06:49 INFO pupa: save organization Michigan Legislature as organization_50bec3d2-f43e-11e9-b509-0242ac120002.json
20:06:49 INFO pupa: save organization Senate as organization_50bec97c-f43e-11e9-b509-0242ac120002.json
20:06:49 INFO pupa: save organization House as organization_50beccce-f43e-11e9-b509-0242ac120002.json
20:06:49 INFO pupa: no session specified, using 2019-2020
20:06:49 INFO scrapelib: GET - http://legislature.mi.gov/doc.aspx?2019-SB-0001
20:06:50 INFO scrapelib: GET - http://www.legislature.mi.gov/documents/2019-2020/Journal/Senate/htm/2019-SJ-05-07-043.htm
20:06:51 WARNING pupa: "In The Chair" indicator not found, unable to extract vote
Traceback (most recent call last):
  File "/opt/openstates/venv-pupa//bin/pupa", line 11, in <module>
    load_entry_point('pupa', 'console_scripts', 'pupa')()
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/__main__.py", line 68, in main
    subcommands[args.subcommand].handle(args, other)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 278, in handle
    return self.do_handle(args, other, juris)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 327, in do_handle
    report['scrape'] = self.do_scrape(juris, args, scrapers)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 175, in do_scrape
    report[scraper_name] = scraper.do_scrape(**scrape_args)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/scrape/base.py", line 112, in do_scrape
    for obj in self.scrape(**kwargs) or []:
  File "/opt/openstates/openstates/openstates/mi/bills.py", line 227, in scrape
    bills = list(self.scrape_bill(chamber, session, bill_id))
  File "/opt/openstates/openstates/openstates/mi/bills.py", line 154, in scrape_bill
    result='pass' if len(results['yes']) > len(results['no']) else 'fail',
TypeError: 'NoneType' object is not subscriptable
```
Appears that the code in MI for parsing bill votes (from roll call documents) returns None if a certain string is not found in the source document, and then None value causes an error in the main bill scraping code.

I am not able to verify that this was the problem causing MI bills not be be present in the OpenStates API data (what happened to bobsled?).

**Comment by jessemortenson** [comment]
Unfortunately it looks like that code change did not fix the issue. MI bill count hasn't changed and confirmed that HB 4852 and SB 452 are still missing.

**Comment by jamesturk** [comment]
There was a hiccup running, I kicked off another run to see if that'll do
it.

I'll update later today

**Comment by jamesturk** [comment]
The scrape is still failing, was it running locally for you?

The error is 
```
17:38:21 INFO pupa: save bill HB 4544 in 2019-2020 as bill_e7f64a08-f5bb-11e9-a9f2-02fc62f468e9.json
17:38:21 INFO scrapelib: GET - http://legislature.mi.gov/doc.aspx?2019-HB-4545
17:38:22 INFO pupa: save bill HB 4545 in 2019-2020 as bill_e89b3aa4-f5bb-11e9-a9f2-02fc62f468e9.json
17:38:22 INFO scrapelib: GET - http://legislature.mi.gov/doc.aspx?2019-HB-4546
17:38:24 INFO pupa: save bill HB 4546 in 2019-2020 as bill_e9dd861a-f5bb-11e9-a9f2-02fc62f468e9.json
17:38:24 INFO scrapelib: GET - http://legislature.mi.gov/doc.aspx?2019-HB-4547
17:38:26 INFO pupa: save bill HB 4547 in 2019-2020 as bill_eb3a9fb6-f5bb-11e9-a9f2-02fc62f468e9.json
17:38:26 INFO scrapelib: GET - http://legislature.mi.gov/doc.aspx?2019-HB-4548
17:38:28 INFO pupa: save bill HB 4548 in 2019-2020 as bill_ec31bc92-f5bb-11e9-a9f2-02fc62f468e9.json
17:38:28 INFO scrapelib: GET - http://legislature.mi.gov/doc.aspx?2019-HB-4549
17:38:29 INFO scrapelib: GET - http://www.legislature.mi.gov/documents/2019-2020/Journal/House/htm/2019-HJ-06-06-058.htm
loaded Open States pupa settings...
mi (scrape, import)
  bills: {}
Traceback (most recent call last):
  File "/opt/openstates/venv-pupa//bin/pupa", line 11, in <module>
    load_entry_point('pupa', 'console_scripts', 'pupa')()
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/__main__.py", line 68, in main
    subcommands[args.subcommand].handle(args, other)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 278, in handle
    return self.do_handle(args, other, juris)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 327, in do_handle
    report['scrape'] = self.do_scrape(juris, args, scrapers)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 175, in do_scrape
    report[scraper_name] = scraper.do_scrape(**scrape_args)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/scrape/base.py", line 112, in do_scrape
    for obj in self.scrape(**kwargs) or []:
  File "/opt/openstates/openstates/openstates/mi/bills.py", line 230, in scrape
    bills = list(self.scrape_bill(chamber, session, bill_id))
  File "/opt/openstates/openstates/openstates/mi/bills.py", line 148, in scrape_bill
    results = self.parse_roll_call(vote_url, rc_num)
  File "/opt/openstates/openstates/openstates/mi/bills.py", line 250, in parse_roll_call
    html = self.get(url).text
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/scrapelib/__init__.py", line 292, in request
    raise HTTPError(resp)
scrapelib.HTTPError: 404 while retrieving http://www.legislature.mi.gov/documents/2019-2020/Journal/House/htm/2019-HJ-06-06-058.htm
```

I can investigate too, but figured I'd share in case this is high priority
(automated posting of these errors is coming back soon, I've been taking the fact most states are in recess to rework a lot of infrastructure)

**Comment by jessemortenson** [comment]
I didn't hit that error, but I also didn't run the whole enchilada, stopped it after I saw some of the missing bills getting processed successfully. I'll take a look at that - thanks!

**Comment by jessemortenson** [comment]
Can confirm my local scrape ran to completion with this latest code change

```
mi (scrape)
  bills: {}
bills scrape:
  duration:  1:03:59.839223
  objects:
    bill: 2070
    vote_event: 438
jurisdiction scrape:
  duration:  0:00:00.022471
  objects:
    jurisdiction: 1
    organization: 3

```

**Comment by jamesturk** [comment]
👍 running again now

**Comment by jessemortenson** [comment]
Thanks! Closing issue: I confirmed that all the missing bills I had identified are now showing up in the API. Total count in the API matches # of bills I saw on local scrape.
